// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "AlbumPresentation.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class AlbumPresentation
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator v17.06.02
// App/Edition: Image Gallery/
// User:        2sic Web-Developer
// When:        2024-04-05 10:52:41Z
namespace AppCode.Data
{
  // This is a generated class for AlbumPresentation 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// AlbumPresentation data. <br/>
  /// Generated 2024-04-05 10:52:41Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.HeadingType`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class AlbumPresentation: AutoGenerated.ZagAlbumPresentation
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.AlbumPresentation in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZagAlbumPresentation: Custom.Data.CustomItem
  {
    /// <summary>
    /// HeadingType as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("HeadingType", scrubHtml: true) etc.
    /// </summary>
    public string HeadingType => _item.String("HeadingType", fallback: "");

    /// <summary>
    /// ShowDescription as bool. <br/>
    /// To get nullable use .Get("ShowDescription") as bool?;
    /// </summary>
    public bool ShowDescription => _item.Bool("ShowDescription");

    /// <summary>
    /// ShowImageTitle as bool. <br/>
    /// To get nullable use .Get("ShowImageTitle") as bool?;
    /// </summary>
    public bool ShowImageTitle => _item.Bool("ShowImageTitle");

    /// <summary>
    /// SortMode as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("SortMode", scrubHtml: true) etc.
    /// </summary>
    public string SortMode => _item.String("SortMode", fallback: "");

    /// <summary>
    /// TileStructure as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("TileStructure", scrubHtml: true) etc.
    /// </summary>
    public string TileStructure => _item.String("TileStructure", fallback: "");
  }
}