// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "Album.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class Album
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator v17.06.02
// App/Edition: Image Gallery/
// User:        2sic Web-Developer
// When:        2024-04-05 10:52:41Z
using ToSic.Sxc.Adam;

namespace AppCode.Data
{
  // This is a generated class for Album 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// Album data. <br/>
  /// Generated 2024-04-05 10:52:41Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.AlbumThumbnail`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class Album: AutoGenerated.ZagAlbum
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.Album in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZagAlbum: Custom.Data.CustomItem
  {
    /// <summary>
    /// AlbumThumbnail as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("AlbumThumbnail")
    /// </summary>
    public string AlbumThumbnail => _item.Url("AlbumThumbnail");

    /// <summary>
    /// Get the file object for AlbumThumbnail - or null if it's empty or not referencing a file.
    /// </summary>
    public IFile AlbumThumbnailFile => _item.File("AlbumThumbnail");

    /// <summary>
    /// Get the folder object for AlbumThumbnail.
    /// </summary>
    public IFolder AlbumThumbnailFolder => _item.Folder("AlbumThumbnail");

    /// <summary>
    /// Images as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("Images")
    /// </summary>
    public string Images => _item.Url("Images");

    /// <summary>
    /// Get the file object for Images - or null if it's empty or not referencing a file.
    /// </summary>
    public IFile ImagesFile => _item.File("Images");

    /// <summary>
    /// Get the folder object for Images.
    /// </summary>
    public IFolder ImagesFolder => _item.Folder("Images");

    /// <summary>
    /// Introduction as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Introduction", scrubHtml: true) etc.
    /// </summary>
    public string Introduction => _item.String("Introduction", fallback: "");

    /// <summary>
    /// Path as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Path", scrubHtml: true) etc.
    /// </summary>
    public string Path => _item.String("Path", fallback: "");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");
  }
}