// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "ImageWithHotspots.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class ImageWithHotspots
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator v17.06.02
// App/Edition: Image Hotspots/
// User:        2sic Web-Developer
// When:        2024-04-04 09:22:07Z
using System.Collections.Generic;
using ToSic.Sxc.Adam;

namespace AppCode.Data
{
  // This is a generated class for ImageWithHotspots 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// ImageWithHotspots data. <br/>
  /// Generated 2024-04-04 09:22:07Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.HotspotMarker`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class ImageWithHotspots: AutoGenerated.ZagImageWithHotspots
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.ImageWithHotspots in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZagImageWithHotspots: Custom.Data.CustomItem
  {
    /// <summary>
    /// HotspotMarker as single item of HotspotMarkers.
    /// </summary>
    /// <remarks>
    /// Generated to only return 1 child because field settings had Multi-Value=false. The type HotspotMarkers was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// A single item OR null if nothing found, so you can use ?? to provide alternate objects.
    /// </returns>
    public HotspotMarkers HotspotMarker => _hotspotMarker ??= _item.Child<HotspotMarkers>("HotspotMarker");
    private HotspotMarkers _hotspotMarker;

    /// <summary>
    /// Hotspots as list of Hotspot.
    /// </summary>
    /// <remarks>
    /// Generated to return child-list child because field settings had Multi-Value=true. The type Hotspot was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// An IEnumerable of specified type, but can be empty.
    /// </returns>
    public IEnumerable<Hotspot> Hotspots => _hotspots ??= _item.Children<Hotspot>("Hotspots");
    private IEnumerable<Hotspot> _hotspots;

    /// <summary>
    /// Image as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("Image")
    /// </summary>
    public string Image => _item.Url("Image");

    /// <summary>
    /// Get the file object for Image - or null if it's empty or not referencing a file.
    /// </summary>
    public IFile ImageFile => _item.File("Image");

    /// <summary>
    /// Get the folder object for Image.
    /// </summary>
    public IFolder ImageFolder => _item.Folder("Image");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");
  }
}