// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "AppResources.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class AppResources
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator v17.06.02
// App/Edition: Jobs/
// User:        2sic Web-Developer
// When:        2024-04-08 07:53:49Z
namespace AppCode.Data
{
  // This is a generated class for AppResources (scope: System.App)
  // To extend/modify it, see instructions above.

  /// <summary>
  /// AppResources data. <br/>
  /// Generated 2024-04-08 07:53:49Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.BtnBack`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  /// <remarks>
  /// This Content-Type is NOT in the default scope, so you may not see it in the Admin UI. It's in the scope System.App.
  /// </remarks>
  public partial class AppResources: AutoGenerated.ZagAppResources
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for System.App.AppResources in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZagAppResources: Custom.Data.CustomItem
  {
    /// <summary>
    /// BtnBack as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("BtnBack", scrubHtml: true) etc.
    /// </summary>
    public string BtnBack => _item.String("BtnBack", fallback: "");

    /// <summary>
    /// BtnRegistration as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("BtnRegistration", scrubHtml: true) etc.
    /// </summary>
    public string BtnRegistration => _item.String("BtnRegistration", fallback: "");

    /// <summary>
    /// CountrySelection as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("CountrySelection", scrubHtml: true) etc.
    /// </summary>
    public string CountrySelection => _item.String("CountrySelection", fallback: "");

    /// <summary>
    /// DatePosted as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("DatePosted", scrubHtml: true) etc.
    /// </summary>
    public string DatePosted => _item.String("DatePosted", fallback: "");

    /// <summary>
    /// LabelAdminDetailPageWarning as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LabelAdminDetailPageWarning", scrubHtml: true) etc.
    /// </summary>
    public string LabelAdminDetailPageWarning => _item.String("LabelAdminDetailPageWarning", fallback: "");

    /// <summary>
    /// LabelApplicationFile as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LabelApplicationFile", scrubHtml: true) etc.
    /// </summary>
    public string LabelApplicationFile => _item.String("LabelApplicationFile", fallback: "");

    /// <summary>
    /// LabelCountry as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LabelCountry", scrubHtml: true) etc.
    /// </summary>
    public string LabelCountry => _item.String("LabelCountry", fallback: "");

    /// <summary>
    /// LabelFirstName as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LabelFirstName", scrubHtml: true) etc.
    /// </summary>
    public string LabelFirstName => _item.String("LabelFirstName", fallback: "");

    /// <summary>
    /// LabelGpdr as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LabelGpdr", scrubHtml: true) etc.
    /// </summary>
    public string LabelGpdr => _item.String("LabelGpdr", fallback: "");

    /// <summary>
    /// LabelJobName as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LabelJobName", scrubHtml: true) etc.
    /// </summary>
    public string LabelJobName => _item.String("LabelJobName", fallback: "");

    /// <summary>
    /// LabelLastName as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LabelLastName", scrubHtml: true) etc.
    /// </summary>
    public string LabelLastName => _item.String("LabelLastName", fallback: "");

    /// <summary>
    /// LabelMail as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LabelMail", scrubHtml: true) etc.
    /// </summary>
    public string LabelMail => _item.String("LabelMail", fallback: "");

    /// <summary>
    /// LabelMobilePhone as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LabelMobilePhone", scrubHtml: true) etc.
    /// </summary>
    public string LabelMobilePhone => _item.String("LabelMobilePhone", fallback: "");

    /// <summary>
    /// LabelMr as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LabelMr", scrubHtml: true) etc.
    /// </summary>
    public string LabelMr => _item.String("LabelMr", fallback: "");

    /// <summary>
    /// LabelMrs as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LabelMrs", scrubHtml: true) etc.
    /// </summary>
    public string LabelMrs => _item.String("LabelMrs", fallback: "");

    /// <summary>
    /// LabelNofilter as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LabelNofilter", scrubHtml: true) etc.
    /// </summary>
    public string LabelNofilter => _item.String("LabelNofilter", fallback: "");

    /// <summary>
    /// LabelNoResults as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LabelNoResults", scrubHtml: true) etc.
    /// </summary>
    public string LabelNoResults => _item.String("LabelNoResults", fallback: "");

    /// <summary>
    /// LabelPhone as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LabelPhone", scrubHtml: true) etc.
    /// </summary>
    public string LabelPhone => _item.String("LabelPhone", fallback: "");

    /// <summary>
    /// LabelRequired as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LabelRequired", scrubHtml: true) etc.
    /// </summary>
    public string LabelRequired => _item.String("LabelRequired", fallback: "");

    /// <summary>
    /// LabelSalutation as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LabelSalutation", scrubHtml: true) etc.
    /// </summary>
    public string LabelSalutation => _item.String("LabelSalutation", fallback: "");

    /// <summary>
    /// LabelSelect as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LabelSelect", scrubHtml: true) etc.
    /// </summary>
    public string LabelSelect => _item.String("LabelSelect", fallback: "");

    /// <summary>
    /// LabelShowMore as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LabelShowMore", scrubHtml: true) etc.
    /// </summary>
    public string LabelShowMore => _item.String("LabelShowMore", fallback: "");

    /// <summary>
    /// LabelStreet as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LabelStreet", scrubHtml: true) etc.
    /// </summary>
    public string LabelStreet => _item.String("LabelStreet", fallback: "");

    /// <summary>
    /// LabelValidEmail as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LabelValidEmail", scrubHtml: true) etc.
    /// </summary>
    public string LabelValidEmail => _item.String("LabelValidEmail", fallback: "");

    /// <summary>
    /// LabelValidFile as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LabelValidFile", scrubHtml: true) etc.
    /// </summary>
    public string LabelValidFile => _item.String("LabelValidFile", fallback: "");

    /// <summary>
    /// LabelZipCity as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LabelZipCity", scrubHtml: true) etc.
    /// </summary>
    public string LabelZipCity => _item.String("LabelZipCity", fallback: "");

    /// <summary>
    /// MailCustomerBody as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("MailCustomerBody", scrubHtml: true) etc.
    /// </summary>
    public string MailCustomerBody => _item.String("MailCustomerBody", fallback: "");

    /// <summary>
    /// MailCustomerSubject as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("MailCustomerSubject", scrubHtml: true) etc.
    /// </summary>
    public string MailCustomerSubject => _item.String("MailCustomerSubject", fallback: "");

    /// <summary>
    /// MailOwnerIntroduction as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("MailOwnerIntroduction", scrubHtml: true) etc.
    /// </summary>
    public string MailOwnerIntroduction => _item.String("MailOwnerIntroduction", fallback: "");

    /// <summary>
    /// MailOwnerSubject as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("MailOwnerSubject", scrubHtml: true) etc.
    /// </summary>
    public string MailOwnerSubject => _item.String("MailOwnerSubject", fallback: "");

    /// <summary>
    /// MessageDefaultMailSettings as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("MessageDefaultMailSettings", scrubHtml: true) etc.
    /// </summary>
    public string MessageDefaultMailSettings => _item.String("MessageDefaultMailSettings", fallback: "");

    /// <summary>
    /// MessageRegistrationDisabled as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("MessageRegistrationDisabled", scrubHtml: true) etc.
    /// </summary>
    public string MessageRegistrationDisabled => _item.String("MessageRegistrationDisabled", fallback: "");

    /// <summary>
    /// MessageSending as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("MessageSending", scrubHtml: true) etc.
    /// </summary>
    public string MessageSending => _item.String("MessageSending", fallback: "");

    /// <summary>
    /// NamePrefix as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("NamePrefix", scrubHtml: true) etc.
    /// </summary>
    public string NamePrefix => _item.String("NamePrefix", fallback: "");

    /// <summary>
    /// NamePrefixList as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("NamePrefixList", scrubHtml: true) etc.
    /// </summary>
    public string NamePrefixList => _item.String("NamePrefixList", fallback: "");

    /// <summary>
    /// OurOfferHeading as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("OurOfferHeading", scrubHtml: true) etc.
    /// </summary>
    public string OurOfferHeading => _item.String("OurOfferHeading", fallback: "");

    /// <summary>
    /// QualificationsHeading as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("QualificationsHeading", scrubHtml: true) etc.
    /// </summary>
    public string QualificationsHeading => _item.String("QualificationsHeading", fallback: "");

    /// <summary>
    /// RegistrationError as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("RegistrationError", scrubHtml: true) etc.
    /// </summary>
    public string RegistrationError => _item.String("RegistrationError", fallback: "");

    /// <summary>
    /// SuccessMessage as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("SuccessMessage", scrubHtml: true) etc.
    /// </summary>
    public string SuccessMessage => _item.String("SuccessMessage", fallback: "");

    /// <summary>
    /// SuccessThanks as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("SuccessThanks", scrubHtml: true) etc.
    /// </summary>
    public string SuccessThanks => _item.String("SuccessThanks", fallback: "");

    /// <summary>
    /// TasksHeading as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("TasksHeading", scrubHtml: true) etc.
    /// </summary>
    public string TasksHeading => _item.String("TasksHeading", fallback: "");

    /// <summary>
    /// ValidationRequired as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("ValidationRequired", scrubHtml: true) etc.
    /// </summary>
    public string ValidationRequired => _item.String("ValidationRequired", fallback: "");
  }
}