// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "EmploymentType.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class EmploymentType
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator v17.06.02
// App/Edition: Jobs/
// User:        2sic Web-Developer
// When:        2024-04-08 07:53:49Z
using System;

namespace AppCode.Data
{
    // This is a generated class for EmploymentType 
    // To extend/modify it, see instructions above.

    /// <summary>
    /// EmploymentType data. <br/>
    /// Generated 2024-04-08 07:53:49Z. Re-generate whenever you change the ContentType. <br/>
    /// <br/>
    /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
    /// Most properties have a simple access, such as `.Key`. <br/>
    /// For other properties or uses, use methods such as
    /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
    /// </summary>
    public partial class EmploymentType : AutoGenerated.ZagEmploymentType
    {
        internal object Select(Func<object, object> value)
        {
            throw new NotImplementedException();
        }
    }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.EmploymentType in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZagEmploymentType: Custom.Data.CustomItem
  {
    /// <summary>
    /// Key as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Key", scrubHtml: true) etc.
    /// </summary>
    public string Key => _item.String("Key", fallback: "");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");
  }
}