// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "TextImageViewSettings.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class TextImageViewSettings
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator v17.06.04
// App/Edition: Call To Action/
// User:        2sic Web-Developer
// When:        2024-04-24 06:57:08Z
namespace AppCode.Data
{
  // This is a generated class for TextImageViewSettings (scope: System.Configuration)
  // To extend/modify it, see instructions above.

  /// <summary>
  /// TextImageViewSettings data. <br/>
  /// Generated 2024-04-24 06:57:08Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.ColsElement`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  /// <remarks>
  /// This Content-Type is NOT in the default scope, so you may not see it in the Admin UI. It's in the scope System.Configuration.
  /// </remarks>
  public partial class TextImageViewSettings: AutoGenerated.ZagTextImageViewSettings
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for System.Configuration.TextImageViewSettings in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZagTextImageViewSettings: Custom.Data.CustomItem
  {
    /// <summary>
    /// ColsElement as int. <br/>
    /// To get other types use methods such as .Decimal("ColsElement")
    /// </summary>
    public int ColsElement => _item.Int("ColsElement");

    /// <summary>
    /// TextFirst as bool. <br/>
    /// To get nullable use .Get("TextFirst") as bool?;
    /// </summary>
    public bool TextFirst => _item.Bool("TextFirst");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");
  }
}