// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "Slider.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class Slider
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator v17.06.02
// App/Edition: Swiper Slider/
// User:        2sic Web-Developer
// When:        2024-04-05 11:31:21Z
using System.Collections.Generic;

namespace AppCode.Data
{
  // This is a generated class for Slider 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// Slider data. <br/>
  /// Generated 2024-04-05 11:31:21Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.AnimationDuration`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class Slider: AutoGenerated.ZagSlider
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.Slider in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZagSlider: Custom.Data.CustomItem
  {
    /// <summary>
    /// AnimationDuration as int. <br/>
    /// To get other types use methods such as .Decimal("AnimationDuration")
    /// </summary>
    public int AnimationDuration => _item.Int("AnimationDuration");

    /// <summary>
    /// Autoplay as bool. <br/>
    /// To get nullable use .Get("Autoplay") as bool?;
    /// </summary>
    public bool Autoplay => _item.Bool("Autoplay");

    /// <summary>
    /// DarkContent as bool. <br/>
    /// To get nullable use .Get("DarkContent") as bool?;
    /// </summary>
    public bool DarkContent => _item.Bool("DarkContent");

    /// <summary>
    /// Effect as single item of Effect.
    /// </summary>
    /// <remarks>
    /// Generated to only return 1 child because field settings had Multi-Value=false. The type Effect was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// A single item OR null if nothing found, so you can use ?? to provide alternate objects.
    /// </returns>
    public Effect Effect => _effect ??= _item.Child<Effect>("Effect");
    private Effect _effect;

    /// <summary>
    /// Height as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Height", scrubHtml: true) etc.
    /// </summary>
    public string Height => _item.String("Height", fallback: "");

    /// <summary>
    /// OverlayEffect as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("OverlayEffect", scrubHtml: true) etc.
    /// </summary>
    public string OverlayEffect => _item.String("OverlayEffect", fallback: "");

    /// <summary>
    /// ShowDuration as int. <br/>
    /// To get other types use methods such as .Decimal("ShowDuration")
    /// </summary>
    public int ShowDuration => _item.Int("ShowDuration");

    /// <summary>
    /// ShowPaginationArrows as bool. <br/>
    /// To get nullable use .Get("ShowPaginationArrows") as bool?;
    /// </summary>
    public bool ShowPaginationArrows => _item.Bool("ShowPaginationArrows");

    /// <summary>
    /// ShowPaginationDots as bool. <br/>
    /// To get nullable use .Get("ShowPaginationDots") as bool?;
    /// </summary>
    public bool ShowPaginationDots => _item.Bool("ShowPaginationDots");

    /// <summary>
    /// Slides as list of Slide.
    /// </summary>
    /// <remarks>
    /// Generated to return child-list child because field settings had Multi-Value=true. The type Slide was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// An IEnumerable of specified type, but can be empty.
    /// </returns>
    public IEnumerable<Slide> Slides => _slides ??= _item.Children<Slide>("Slides");
    private IEnumerable<Slide> _slides;

    /// <summary>
    /// TextPosition as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("TextPosition", scrubHtml: true) etc.
    /// </summary>
    public string TextPosition => _item.String("TextPosition", fallback: "");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");

    /// <summary>
    /// VarShowSlides as bool. <br/>
    /// To get nullable use .Get("VarShowSlides") as bool?;
    /// </summary>
    public bool VarShowSlides => _item.Bool("VarShowSlides");

    /// <summary>
    /// Width as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Width", scrubHtml: true) etc.
    /// </summary>
    public string Width => _item.String("Width", fallback: "");
  }
}