// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "Slide.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class Slide
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator v17.06.02
// App/Edition: Swiper Slider/
// User:        2sic Web-Developer
// When:        2024-04-05 11:31:21Z
using ToSic.Sxc.Adam;

namespace AppCode.Data
{
  // This is a generated class for Slide 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// Slide data. <br/>
  /// Generated 2024-04-05 11:31:21Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.DarkContent`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class Slide: AutoGenerated.ZagSlide
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.Slide in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZagSlide: Custom.Data.CustomItem
  {
    /// <summary>
    /// DarkContent as bool. <br/>
    /// To get nullable use .Get("DarkContent") as bool?;
    /// </summary>
    public bool DarkContent => _item.Bool("DarkContent");

    /// <summary>
    /// Image as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("Image")
    /// </summary>
    public string Image => _item.Url("Image");

    /// <summary>
    /// Get the file object for Image - or null if it's empty or not referencing a file.
    /// </summary>
    public IFile ImageFile => _item.File("Image");

    /// <summary>
    /// Get the folder object for Image.
    /// </summary>
    public IFolder ImageFolder => _item.Folder("Image");

    /// <summary>
    /// Link as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("Link")
    /// </summary>
    public string Link => _item.Url("Link");

    /// <summary>
    /// LinkBlankTarget as bool. <br/>
    /// To get nullable use .Get("LinkBlankTarget") as bool?;
    /// </summary>
    public bool LinkBlankTarget => _item.Bool("LinkBlankTarget");

    /// <summary>
    /// Get the file object for Link - or null if it's empty or not referencing a file.
    /// </summary>
    public IFile LinkFile => _item.File("Link");

    /// <summary>
    /// Get the folder object for Link.
    /// </summary>
    public IFolder LinkFolder => _item.Folder("Link");

    /// <summary>
    /// LinkText as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LinkText", scrubHtml: true) etc.
    /// </summary>
    public string LinkText => _item.String("LinkText", fallback: "");

    /// <summary>
    /// OverlayEffect as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("OverlayEffect", scrubHtml: true) etc.
    /// </summary>
    public string OverlayEffect => _item.String("OverlayEffect", fallback: "");

    /// <summary>
    /// ShowDuration as int. <br/>
    /// To get other types use methods such as .Decimal("ShowDuration")
    /// </summary>
    public int ShowDuration => _item.Int("ShowDuration");

    /// <summary>
    /// Text as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Text", scrubHtml: true) etc.
    /// </summary>
    public string Text => _item.String("Text", fallback: "");

    /// <summary>
    /// TextPosition as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("TextPosition", scrubHtml: true) etc.
    /// </summary>
    public string TextPosition => _item.String("TextPosition", fallback: "");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");
  }
}