// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "Term.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class Term
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator v17.06.02
// App/Edition: Glossary/
// User:        2sic Web-Developer
// When:        2024-04-04 16:01:08Z
using ToSic.Sxc.Adam;

namespace AppCode.Data
{
  // This is a generated class for Term 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// Term data. <br/>
  /// Generated 2024-04-04 16:01:08Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Abbreviation`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class Term: AutoGenerated.ZagTerm
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.Term in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZagTerm: Custom.Data.CustomItem
  {
    /// <summary>
    /// Abbreviation as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Abbreviation", scrubHtml: true) etc.
    /// </summary>
    public string Abbreviation => _item.String("Abbreviation", fallback: "");

    /// <summary>
    /// abc as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("abc")
    /// </summary>
    public string abc => _item.Url("abc");

    /// <summary>
    /// Get the file object for abc - or null if it's empty or not referencing a file.
    /// </summary>
    public IFile abcFile => _item.File("abc");

    /// <summary>
    /// Get the folder object for abc.
    /// </summary>
    public IFolder abcFolder => _item.Folder("abc");

    /// <summary>
    /// Details as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Details", scrubHtml: true) etc.
    /// </summary>
    public string Details => _item.String("Details", fallback: "");

    /// <summary>
    /// Summary as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Summary", scrubHtml: true) etc.
    /// </summary>
    public string Summary => _item.String("Summary", fallback: "");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");

    /// <summary>
    /// UrlKey as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("UrlKey", scrubHtml: true) etc.
    /// </summary>
    public string UrlKey => _item.String("UrlKey", fallback: "");
  }
}