// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "Facts.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class Facts
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator v17.06.03
// App/Edition: Counter/
// User:        2sic Web-Developer
// When:        2024-04-23 16:56:34Z
namespace AppCode.Data
{
  // This is a generated class for Facts 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// Facts data. <br/>
  /// Generated 2024-04-23 16:56:34Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Icon`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class Facts: AutoGenerated.ZagFacts
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.Facts in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZagFacts: Custom.Data.CustomItem
  {
    /// <summary>
    /// Icon as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Icon", scrubHtml: true) etc.
    /// </summary>
    public string Icon => _item.String("Icon", fallback: "");

    /// <summary>
    /// Number as int. <br/>
    /// To get other types use methods such as .Decimal("Number")
    /// </summary>
    public int Number => _item.Int("Number");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");

    /// <summary>
    /// Unit as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Unit", scrubHtml: true) etc.
    /// </summary>
    public string Unit => _item.String("Unit", fallback: "");
  }
}