// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "Iframe.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class Iframe
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator v17.06.02
// App/Edition: IFrame/
// User:        2sic Web-Developer
// When:        2024-04-04 14:28:27Z
using ToSic.Sxc.Adam;

namespace AppCode.Data
{
  // This is a generated class for Iframe 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// Iframe data. <br/>
  /// Generated 2024-04-04 14:28:27Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.EmbedURL`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class Iframe: AutoGenerated.ZagIframe
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.Iframe in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZagIframe: Custom.Data.CustomItem
  {
    /// <summary>
    /// EmbedURL as link (url). <br/>
    /// To get the underlying value like 'file:72' use String("EmbedURL")
    /// </summary>
    public string EmbedURL => _item.Url("EmbedURL");

    /// <summary>
    /// Get the file object for EmbedURL - or null if it's empty or not referencing a file.
    /// </summary>
    public IFile EmbedURLFile => _item.File("EmbedURL");

    /// <summary>
    /// Get the folder object for EmbedURL.
    /// </summary>
    public IFolder EmbedURLFolder => _item.Folder("EmbedURL");

    /// <summary>
    /// EnableScrollbar as bool. <br/>
    /// To get nullable use .Get("EnableScrollbar") as bool?;
    /// </summary>
    public bool EnableScrollbar => _item.Bool("EnableScrollbar");

    /// <summary>
    /// Height as int. <br/>
    /// To get other types use methods such as .Decimal("Height")
    /// </summary>
    public int Height => _item.Int("Height");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");

    /// <summary>
    /// Width as int. <br/>
    /// To get other types use methods such as .Decimal("Width")
    /// </summary>
    public int Width => _item.Int("Width");
  }
}