// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "Style.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class Style
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator v17.06.02
// App/Edition: Snippet Inject (HTML, CSS, JS)/
// User:        2sic Web-Developer
// When:        2024-04-04 14:57:50Z
namespace AppCode.Data
{
  // This is a generated class for Style 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// Style data. <br/>
  /// Generated 2024-04-04 14:57:50Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Notes`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class Style: AutoGenerated.ZagStyle
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.Style in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZagStyle: Custom.Data.CustomItem
  {
    /// <summary>
    /// Notes as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Notes", scrubHtml: true) etc.
    /// </summary>
    public string Notes => _item.String("Notes", fallback: "");

    /// <summary>
    /// Styles as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Styles", scrubHtml: true) etc.
    /// </summary>
    public string Styles => _item.String("Styles", fallback: "");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");
  }
}